openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://api.test'
paths:
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: ''
                  example: enim
                last_name:
                  type: string
                  description: ''
                  example: quis
                gender:
                  type: string
                  description: 'Must be one of <code>m</code> or <code>f</code>.'
                  example: m
                birth_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-07-26T13:26:51'
                avatar:
                  type: string
                  format: binary
                  description: 'Must be an image.'
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: andrew.marks@example.net
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: sH!Rjm<
              required:
                - first_name
                - last_name
                - gender
                - email
      security: []
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: matilde.krajcik@example.org
                password:
                  type: string
                  description: ''
                  example: molestiae
              required:
                - email
                - password
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/me:
    get:
      summary: ''
      operationId: getApiAuthMe
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/auth/password/email:
    post:
      summary: ''
      operationId: postApiAuthPasswordEmail
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: lwalsh@example.org
              required:
                - email
      security: []
  /api/auth/password/reset:
    post:
      summary: ''
      operationId: postApiAuthPasswordReset
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: ''
                  example: hic
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: goldner.kamren@example.com
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: 'IRHdPJ7>*i6YS~P=Y2p'
              required:
                - token
                - email
                - password
      security: []
  /api/companies:
    get:
      summary: ''
      operationId: getApiCompanies
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiCompanies
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/companies/{id}':
    get:
      summary: ''
      operationId: getApiCompaniesId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiCompaniesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiCompaniesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the company.'
        example: molestiae
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
